### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'stdin'

### ISSUE THREAD

**Issue by eelkeh** [mhartington/nvim-typescript#34] opened 2017-01-04 17:37 UTC
From `:messages`
```
[deoplete]     Client.__server_handle.stdin.write(json.dumps(data))
[deoplete] AttributeError: 'NoneType' object has no attribute 'stdin'
[deoplete] Could not get completions from: typescript.  Use :messages for error details.``
```
Deoplete log:
```
2017-01-04 18:28:15,849 INFO     (deoplete.logging) --- Deoplete Log Start ---
2017-01-04 18:28:15,849 INFO     (deoplete.logging) NVIM 0.1.7, Python 3.5.2, neovim client 0.1.12
2017-01-04 18:28:24,264 DEBUG    (deoplete.typescript) Request: {"command": "reload", "type": "request", "seq": 0, "arguments": {"tmpfile": "/var/folders/_2/s71xc7jn1l36zzc4_wtdf3hr0000gn/T/tmpp2_4nhuf", "file": "/src/app.ts"}}
:^[;^[2017-01-04 18:35:00,123 DEBUG    (deoplete.typescript) Request: {"command": "reload", "type": "request", "seq": 1, "arguments": {"tmpfile": "/var/folders/_2/s71xc7jn1l36zzc4_wtdf3hr0000gn/T/tmpi2xovfdq", "file": "/src/app.ts"}}
```
init.vim:
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#auto_complete_start_length = 0
let g:auto_complete_start_length = 0
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

**Comment by mhartington** [comment] 2017-01-04 17:48
How could I recreate this? 
Is there a sample project to view? What were you trying to  do?

**Comment by eelkeh** [comment] 2017-01-04 18:27
Minimal init.vim to reproduce:
```
" set the runtime path to include Vundle and initialize
call plug#begin('~/.nvim/bundle')

" typescript
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/deoplete-typescript'

call plug#end()

" Use deoplete.
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#auto_complete_start_length = 0
let g:auto_complete_start_length = 0
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```
Versions:

- NVIM 0.1.7
- Python 3.5.2
- neovim client 0.1.12
- Typescript 2.0.10

Is there any other way I can debug this further?

**Comment by mhartington** [comment] 2017-01-04 19:50
Do you have a sample project to test against? 

Normally this means 
A) Typescript project misconfiguration 
B) No TSCONFIG
C) Server is frozen

**Comment by eelkeh** [comment] 2017-01-04 20:02
This is my tsconfig.json:
```
{
    "compilerOptions": {
	"rootDir": "src",
	"outDir": "dist",
        "noImplicitAny": true,
        "strictNullChecks": true,
        "allowJs": false,
        "target": "es5",
        "module": "commonjs",
        "lib": [
            "es5",
            "es2015.promise"
        ]
    },
    "filesGlob": [
        "src/**/*.ts"
    ]
```
When I start typing in any (or empty) `.ts` file the error pops up.

**Comment by eelkeh** [comment] 2017-01-04 20:13
It seems like `tsserver` is never started.

**Comment by sijad** [comment] 2017-01-04 20:14
I have exactly the same problem, this my tsconfig.json

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

typescript version:
```
$ tsc -v
Version 2.1.4
```

I use VimPlug

**Comment by mhartington** [comment] 2017-01-04 20:16
Are you starting vim in the directory that the tsconfig exist in? Or a sub directory?

**Comment by eelkeh** [comment] 2017-01-04 20:19
Same directory, also I can run `tsserver` in the directory where the config exists.
But when running neovim `tsserver` doesn't seem to run (`ps | grep tsserver`)

**Comment by mhartington** [comment] 2017-01-04 20:20
I'll take a look later tonight, need to wrap up work

**Comment by eelkeh** [comment] 2017-01-04 20:21
Thanks for having a look, let me know if you have any pointers so I can debug this any further, or if I can provide any more information for you to look at!

**Comment by sijad** [comment] 2017-01-04 20:30
I also tried with ts 2.0.0 but same problem.

**Comment by sijad** [comment] 2017-01-04 21:38
running `:UpdateRemotePlugins` and restarting nvim fixed this issue for me.

**Comment by mhartington** [comment] 2017-01-04 21:47
Note: Also update the repo name in your rc files.... `mhartington/nvim-typescript`

**Comment by mhartington** [comment] 2017-01-08 23:46
@eelkeh can you provide a sample project which would recreate this issue?

**Comment by DonnieWest** [comment] 2017-01-09 00:41
I had this same issue today. I ended up having to completely reinstall the project from scratch to fix it. In my case, removing it from my init.vim, running `:PlugClean`, putting it back in my init.vim, running `:PlugInstall` and finally `:UpdateRemotePlugins`. 

Seems like it's the result of some sort of cached files from a previous version

**Comment by codyjroberts** [comment] 2017-01-15 00:46
Same issue for me on a fresh angular cli project -- `ng new whatever`. @DonnieWest's solution doesn't work for me.  Interestingly I had no problems with it working with the downloaded tour-of-heroes tutorial.

**Comment by mkrawiec** [comment] 2017-01-15 13:56
angular-cli puts tsconfig.json is in <root>/src you need to symlink it <root>/ for this plugin to work.

> Currently, this plugin requires a tsconfig.json to be present in the current working directory.

Would be nice if we can configure this tho.

**Comment by mhartington** [comment] 2017-01-15 22:44
Hmmm, ok, if thats the case, the check I put in for tsconfig could be bypassed for now. TSServer will actually pick up any tsconfig.json, based on the file path. So even if it's not in the working directory, it will "just work".

Though that check was added to make sure people get completions and plugin functionality... 🤔

**Comment by mhartington** [comment] 2017-01-15 22:45
I just pushed a fix for this. Please pull the latest version and test.

**Comment by timshannon** [comment] 2017-01-20 15:17
I'm getting the same issue on a brand new install pulled from master.  My plugin manage is pathogen.

My tsconfig.json literally only has one file entry point and no compiler options, so they would all be the defaults.  Does this plugin require anything else specifically in the tsconfig for it to work?

**Comment by mhartington** [comment] 2017-02-02 21:53
@timshannon could you provide a sample project? This is mostly related to server communication and I am unable to reproduce at all.

**Comment by timshannon** [comment] 2017-02-03 14:57
sure let me throw together a minimal project and see if I can get it working, but I suspect it has to do with the environment, and not the project.

**Comment by timshannon** [comment] 2017-02-05 21:41
So as minimal as I could get:

index.ts
```typescript
let test: string;

```

tsconfig.json
```json
{
    "files": [
        "index.ts"
    ]
}
```

When I startup nvim in this directory, it says the tsserver is started, then I start typing at the bottom of index.ts, and I start getting the errors above.

Even though it says tsserver is started, I'm not seeing it running.  I can run tsserver on it's own with no failure, so I'm not sure why it's starting and failing in nvim-typescript.

**Comment by mhartington** [comment] 2017-02-09 14:23
whats you're global typescript install version?

```bash
tsc -v
```

I'm unable to reproduce with 2.0.9.

**Comment by timshannon** [comment] 2017-02-09 14:24
Version 2.1.5

**Comment by mhartington** [comment] 2017-02-09 14:36
Just upgraded and I am unable to reproduce. 
Please provide a minimal vimrc and a sample project.

**Comment by mhartington** [comment] 2017-02-13 22:50
can everyone pull and update the lastest commit

**Comment by mhartington** [comment] 2017-02-15 21:35
Closing as I have not been able to reproduce.

**Closed by mhartington** 2017-02-15 21:35 UTC
Labels: cannot reproduce

**Comment by ohjames** [comment] 2017-04-09 01:45
Same issue here with tsc 2.1.6, plugin is not usable in three out of three of my typescript projects.

**Comment by ohjames** [comment] 2017-04-09 01:47
@mhartington I'm not quite sure, are you saying we have to downgrade to typescript 2.0 for this plugin to work?

**Comment by ohjames** [comment] 2017-04-09 15:21
@mhartington Found the issue, check: http://stackoverflow.com/questions/5658622/python-subprocess-popen-environment-path

It's a very simple fix.

**Comment by mhartington** [comment] 2017-04-09 15:59
Please move this to a new issue. This current issue is closed. Also, if you're able, please make a Pull Request, as I'm traveling currently 

Mike Hartington
