### ISSUE TITLE
Lost TSSyncErr in refactor

### ISSUE THREAD

**Issue by dlants** [mhartington/nvim-typescript#134] opened 2018-05-30 17:51 UTC
# Problems summary
The `TSSyncErr` command introduced in this PR https://github.com/mhartington/nvim-typescript/pull/53 is no longer defined. Looks like it was lost in this refactor https://github.com/mhartington/nvim-typescript/commit/6c67a845c98306f4b1adfd18aa80fb0255901a1f

## Expected
Fast error checks with `TSSyncErr`, or some alternative that takes advantage of
`syntacticDiagnosticsSync` and `semanticDiagnosticsSync` tsserver commands.

**Comment by mhartington** [comment] 2018-05-30 18:08
Hey thanks for the heads up! Since I haven't been able to make progress on integrating with ALE or neomake, I think I might have to make a simple little linting/sing column piece. This could better integrate with tsserver and only provide feedback for the current open file, vs neomake/ale having to run `tsc` against an entire project. This is how VSCode does things and why it's fast.

**Comment by dlants** [comment] 2018-05-30 18:15
`nvim_buf_add_highlight` (in combination with populating the location list) works well and is easy to implement -- documented here https://github.com/neovim/neovim/blob/master/runtime/doc/api.txt

You can see how I used it with python in PR #53. I imagine the node neovim client has a similar binding.

**Comment by dlants** [comment] 2018-05-30 18:16
I'm also happy to take a stab at it once the python -> ts conversion lands. :)

**Comment by mhartington** [comment] 2018-06-04 00:44
Making some progress 😄 

![diagnostic](https://user-images.githubusercontent.com/2835826/40893164-93be6e5c-676e-11e8-83c1-052902f41c50.gif)

Right now Im placing signs and able to remove/update them as needed, plus add highlights too.
Going to push to a branch probably in the morning, but it's looking good. Next part is to figure out how to print the error message.

**Comment by mhartington** [comment] 2018-06-11 15:40
working on solidifying a few more things, but would love for folks to check out the work so far!

https://github.com/mhartington/nvim-typescript/tree/feat-diagnostics

**Comment by dlants** [comment] 2018-06-11 20:19
install is failing for me:

```
/.vim/plugged/nvim-typescript/rplugin/node/nvim_typescript ❯❯❯ ./node_modules/.bin/tsc                                                                                                                                                                                                                                                                                                                                                                              ✘ 127 feat-diagnostics ✱
src/index.ts:29:7 - error TS2345: Argument of type 'VimValue' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

29       await this.nvim.getVar('nvim_typescript#max_completion_detail')
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/index.ts:34:31 - error TS2345: Argument of type 'VimValue' is not assignable to parameter of type 'string'.
  Type 'number' is not assignable to type 'string'.

34     this.client.setServerPath(serverPath);
                                 ~~~~~~~~~~


src/utils.ts:141:20 - error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

141   if (msg.length > columns - 12) {
                       ~~~~~~~


src/utils.ts:142:28 - error TS2362: The left-hand side of an arithmetic operation must be of type 'any', 'number' or an enum type.

142     msg = msg.substring(0, columns - 15) + '...';
                               ~~~~~~~
```

**Comment by mhartington** [comment] 2018-06-11 20:30
Sorry about that! Look like neovim client updated some type info.  Can you pull down and try again?

**Comment by dlants** [comment] 2018-06-11 21:21
Ok, seems to be loading now (also needed to `:UpdateRemotePlugins` in addition to `./install.sh` in the installation instructions).

The "dot" decorators are showing up for me, and I'm seeing the error message echo when I place the cursor on the error.

Some notes:

- I am not seeing highlighting happen... calling `synstack` (from here https://stackoverflow.com/a/9464929/9621241 ) on the error doesn't show an error hl group on top of the error.
- The sign + loc list are not cleared when I fix the last error in a buffer.

**Comment by dlants** [comment] 2018-06-11 21:29
actually, the sign/loc list clearing doesn't have anything to do with it being the last error. It seems that errors are only cleared when a new error is introduced, or when an error changes lines. If I only fix errors in-place (say, fixing a typo), then multiple error signs and locations persist.

**Comment by pyrho** [comment] 2018-06-11 23:03
Gave it a try and it works like a charm for me.
The only issue I'm having is that sometimes the error does not `:echo`. My location list and gutter signs are otherwise working flawlessly.

I will use this branch as my main and keep you posted if I encounter any issue !

Thank you again for all your hard work ! :)

**Comment by mhartington** [comment] 2018-06-15 13:56
I pushed a fix for some issues I was seeing, where errors were being reported in html files, which was unexpected.

Please let me know if you see any issues showing up. If there are none, I think I might call this done!

**Comment by megalithic** [comment] 2018-06-18 14:59
@mhartington thanks so much for this feature. I'll "echo" what @pyrho was reporting; that is, i see the gutter signs, but no "echoing" of the error/warning/info details when cursor is on that line.

**Comment by mhartington** [comment] 2018-06-18 16:43
Hm, I'm seeing them locally, so not sure what could be the cause of the issue. I'll investigate more this week.

**Comment by megalithic** [comment] 2018-06-18 18:03
@mhartington mind sharing your latest neovim config? Wondering if something with ale and/or languageclient could be fouling things up.

**Comment by mhartington** [comment] 2018-06-18 18:08
https://gist.github.com/mhartington/c2e26b04010fa7bcf946aa9341b90a68

I've disabled neomake for typescript and the LanguageClient as well.

**Comment by megalithic** [comment] 2018-06-18 18:37
@mhartington ok sir, after fiddling a bit more, it seems to work the first time you open neovim + buffers. where it seems to fall apart, is say you have an unused import, you remove that line, now, it no longer echoes the error/warning for other lines in the buffer. as soon as i completely exit neovim, and re-open those some files, it seems to work again (until i make a change in the buffer again).

i hope that helps!

**Comment by mhartington** [comment] 2018-06-18 18:52
Might sounds a bitch much...but could you make a quick sample project to test?

**Comment by megalithic** [comment] 2018-06-18 19:09
yeah, i'll do my best to get something put together today. thanks much Mike. you're good peoples.

**Comment by mhartington** [comment] 2018-06-19 13:27
*just realizing my previous comment had a type that made it sound.....too aggressive*

So sorry about that @megalithic ! I meant to say a **bit much**...

**Comment by megalithic** [comment] 2018-06-19 14:02
hah, no worries champ. no aggro taken from your response.

**Comment by mhartington** [comment] 2018-06-19 14:28
So I debugged this as much as I could last night and wasn't able to recreate your issue with echos not appearing.



[![](http://i3.ytimg.com/vi/7QJWJQHDgCA/maxresdefault.jpg)](https://youtu.be/7QJWJQHDgCA)

_Youtube Video_


It all seems to be working fine for me

**Comment by megalithic** [comment] 2018-06-19 14:34
thanks @mhartington i'm going to just do more digging into my config too. also, side note, how are you handling linting/fixing for things other than what's defined in your tsconfig? example being, being on a a project that has a robust eslintrc using eslint-typescript and eslint-prettier?

thanks again for digging in further; no need to spend more time on my specific issue, because i really do think it's just a combo of ALE + languageclient + nvim-typescript. I want to fiddle with nvim-typescript and see if it handles issues raised from eslint/eslint-prettier/eslint-typescript and might just have to manually run my fixer, instead of relying on ALE doing it on save or text change.

**Comment by mhartington** [comment] 2018-06-19 14:42
I've been playing with the idea of adding a code-fix action, similar to vscodes. 
TSServer supports this, so the functionality is there, just need to be able to define a symbols start and end column, which not sure how to get the end column in viml 🤔 

As for eslint...not sure what can be done there, but tslint does support integration with typescripts language service 

https://github.com/angelozerr/tslint-language-service

With this, nvim-typescirpt could hook into code-fixes from tslint, as they get processed in the tsserver side of things.

For prettier, I just use neoformat 🤷‍♂️ , not sure formatting is something I want to get into right now

**Comment by megalithic** [comment] 2018-06-19 19:33
@mhartington you are a hero! i realized what was happening. looking at your demo  video of the diagnostics behavior, you're highlighting exact words/characters that are in question with the error/warning/info; so that when cursor is in those word boundaries you see the echo'd warning/error/info.... well, unfortunately i don't have highlighting setup like that, so i was just putting the cursor on the line where the gutter marker shows, and of course i'm not going to see anything echoed. doh!

anyway, i'm going to give your dotfiles a look to see if you're doing anything specific with error highlighting.

thanks again for your patience with looking into things and apologies for my ignorance with using your plugin (rather, not using it correctly).

**Comment by megalithic** [comment] 2018-06-19 20:35
@mhartington I'm super close. have you see where the echomessage will disappear as fast as the cursor goes onto the word in question? in otherwords, say you put your cursor in the word boundary of a, say word that isn't used anywhere in the file (like with your youtube demo), i see the echoed message, then it immediately disappears. subsequent `:message` commands shows me that echoed message in the listing. I know this is not at the fault of your plugin, just curious if you've seen this and have fixed something similar.

Thanks again!

**Comment by mhartington** [comment] 2018-07-09 01:42
This is now in master!

**Closed by mhartington** 2018-07-09 01:42 UTC
