### ISSUE TITLE
high cpu use tsserver

### ISSUE THREAD

**Issue by fpereira1** [mhartington/nvim-typescript#236] opened 2019-06-14 02:20 UTC
I often get really high CPU usage with a number of these processes showing on `htop`
```
node node_modules/.bin/tsserver --disableAutomaticTypingAcquisition
```
Killing all node processes fix the issue, and brings back the machine to a useable state.
Anyone noticing this or a way to debug the issue?

**Comment by gunar** [comment] 2020-10-21 12:01
I'm wondering if the bundler and neovim are creating each their own ts server instead of sharing a single one

**Comment by gunar** [comment] 2020-10-21 18:06
Yeah they definitely don't share a single ts server.

But more importantly, I can see my NeoVim spawning two `tsserver`s.
One "directly" and one through "neovim-node-host".

**Comment by mhartington** [comment] 2020-10-21 18:07
minimal example?

**Comment by gunar** [comment] 2020-10-21 18:07
Yup, let me get that for you.

**Comment by gunar** [comment] 2020-10-22 11:20
My case is a dupe of #232. OP might have a different problem.

**Comment by fpereira1** [comment] 2020-10-22 21:27
The orignial issue I reported was mostly fixed by an upgrade to typescript 4. I later discovered that I would only notice this issue after an npm install. Related to this https://github.com/microsoft/TypeScript/issues/37653
So I believe this issue can be closed.

**Closed** 2020-10-23 12:30 UTC
