### ISSUE TITLE
"unknown function sign_define" error occurs

### ISSUE THREAD

**Issue by musou1500** [mhartington/nvim-typescript#242] opened 2019-07-21 00:39 UTC
# Problems summary
"Unknown function: sign_define" error occurs.
here is a entire error.

```
2019-07-21T00:26:34.813Z - error: Error in plugin for function:TSOnBufEnter: nvim_call_function: Vim:E117: Unknown function: sign_define (file: /home/xxxx/.local/share/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript, stack: Error: nvim_call_function: Vim:E117: Unknown function: sign_define
    at transport.request (/home/xxxx/.local/share/nvm/versions/node/v10.16.0/lib/node_modules/neovim/lib/api/Base.js:31:28)
    at Transport.parseMessage (/home/xxxx/.local/share/nvm/versions/node/v10.16.0/lib/node_modules/neovim/lib/utils/transport.js:96:13)
    at DecodeStream.Transport.decodeStream.on (/home/xxxx/.local/share/nvm/versions/node/v10.16.0/lib/node_modules/neovim/lib/utils/transport.js:37:18)
    at DecodeStream.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at DecodeStream.Readable.push (_stream_readable.js:224:10)
    at DecodeStream.Transform.push (_stream_transform.js:151:32)
    at DecodeBuffer.DecodeStream.decoder.push (/home/xxxx/.local/share/nvm/versions/node/v10.16.0/lib/node_modules/neovim/node_modules/msgpack-lite/lib/decode-stream.js:24:12)
    at DecodeBuffer.flush (/home/xxxx/.local/share/nvm/versions/node/v10.16.0/lib/node_modules/neovim/node_modules/msgpack-lite/lib/flex-buffer.js:57:12))
```

## Environment Information

 * terminal: gnome-terminal 3.28.2
 * vim/nvim version: NVIM v0.3.7 (I installed it from apt)

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/nvim-typescript

let $NVIM_NODE_LOG_FILE='nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='warn'

```

## The reproduce ways from neovim starting

 1. open typescript file with neovim
 2. open log file

**Comment by deltaskelta** [comment] 2019-07-21 01:41
I am seeing this as well...

There is also no running tsserver when I check, so the plugin doesn't do anything

**Comment by musou1500** [comment] 2019-07-21 02:02
@deltaskelta May I ask about your environment information?
* neovim version
* os
* how you installed neovim(package manager,  from source...etc)

**Comment by deltaskelta** [comment] 2019-07-21 02:15
```
NVIM 0.3.8
OS Mojave 10.14.5
```
Installed from Homebrew

It looks like `sign_define` may have recently changed in vim... https://github.com/vim/vim/issues/4557

**Comment by deltaskelta** [comment] 2019-07-21 02:28
If I revert this change, it fixes the problem and allows the server to start, but then I get other similar errors down the line which makes me think that maybe something in the author @mhartington environment is different

**Comment by musou1500** [comment] 2019-07-21 02:55
@deltaskelta thank you.

@mhartington 
I noticed that currently `sign_*` functions are available only nightly version of neovim.
I think to use `sign` commands instead can be a solution.
Is there any benefit to using a function?

**Comment by deltaskelta** [comment] 2019-07-21 03:53
I ended up switching to the nightly because I wanted to try out some new denite stuff and I can confirm that the nightly 0.4.0 works

**Comment by mhartington** [comment] 2019-07-21 16:39
Upgrade to the nightly release (which will be released soon).

The new sign API and floating API is also part of the nightly release, not 0.3.8, so it mades sense. 

Going to close this for now, but will point other here for reference.

**Closed by mhartington** 2019-07-21 16:39 UTC

**Comment by smumu** [comment] 2019-07-29 08:16
Hi,
I have the same error (Neovim 0.3.8). I see the [0.4.0 milestone](https://github.com/neovim/neovim/milestone/21) has been moved to August 20. It seems a bit long so maybe a fix, maybe in a specific branch (started from a working revision), could be made to have a working plugin during the 3 next weeks for those who don't use the nightly release? 
Thanks in advance!
